title: Various Shares
description: Various shares from around the net
baseurl: ""
url: https://shared.paultraylor.net
twitter_username: kfdm
github_username: kfdm

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
